module.exports =
  mammals:
    aardvark: require './aardvark'
    baboon: require './baboon'
    buffalo: require './buffalo'
    bushbuck: require './bushbuck'
    bushpig: require './bushpig'
    caracal: require './caracal'
    civet: require './civet'
    duiker: require './duiker'
    eland: require './eland'
    elephant: require './elephant'
    genet: require './genet'
    hare: require './hare'
    hartebeest: require './hartebeest'
    hippopotamus: require './hippopotamus'
    honeybadger: require './honey-badger'
    hyena: require './hyena'
    impala: require './impala'
    jackal: require './jackal'
    kudu: require './kudu'
    leopard: require './leopard'
    lion: require './lion'
    mongoose: require './mongoose'
    nyala: require './nyala'

  birds:
    crane: require './crane'
  reptiles:
    crocodile: require './crocodile'
    tortoise: require './tortoise'
