module.exports =
  mammals:
    aardvark: require './aardvark'
    baboon: require './baboon'
    buffalo: require './buffalo'
    bushbuck: require './bushbuck'
    bushpig: require './bushpig'
    caracal: require './caracal'
    civet: require './civet'
    duiker: require './duiker'
    eland: require './eland'
    elephant: require './elephant'
    genet: require './genet'
    hare: require './hare'
    hartebeest: require './hartebeest'
    hippopotamus: require './hippopotamus'
    honeybadger: require './honey-badger'
    hyena: require './hyena'
    impala: require './impala'
    jackal: require './jackal'
    kudu: require './kudu'
    leopard: require './leopard'
    #lion: require './lion'
    mongoose: require './mongoose'
    nyala: require './nyala'
    oribi: require './oribi'
    otter: require './otter'
    pangolin: require './pangolin'
    porcupine: require './porcupine'
    reedbuck: require './reedbuck'
    sable: require './sable'
    #samango_monkey: require './samango_monkey'
    serval: require './serval'
    vervet: require './vervet'
    warthog: require './warthog'
    waterbuck: require './waterbuck'
    weasel: require './weasel'
    wild_dog: require './wild-dog'
    wildcat: require './wildcat'
    wildebeest: require './wildebeest'
    zebra: require './zebra'

  birds:
    crane: require './crane'
    ground_hornbill: require './ground_hornbill'

  reptiles:
    reptile: require './reptile'
    #crocodile: require './crocodile'
    #tortoise: require './tortoise'
