module.exports =
  mammals:
    aardvark: require './aardvark'
    baboon: require './baboon'
    buffalo: require './buffalo'
    bushbuck: require './bushbuck'
    bushpig: require './bushpig'
    caracal: require './caracal'
    civet: require './civet'
    duiker: require './duiker'
    eland: require './eland'
    elephant: require './elephant'
    genet: require './genet'
    hare: require './hare'
    hartebeest: require './hartebeest'
    hippopotamus: require './hippopotamus'
    honey_badger: require './honey_badger'
    hyena: require './hyena'
    impala: require './impala'
    jackal: require './jackal'
    kudu: require './kudu'
    leopard: require './leopard'
    lion_female: require './lion_female'
    #lion_male: require './lion_male'
    #lion_cub: require './lion_cub'
    mongoose: require './mongoose'
    nyala: require './nyala'
    oribi: require './oribi'
    otter: require './otter'
    pangolin: require './pangolin'
    porcupine: require './porcupine'
    reedbuck: require './reedbuck'
    sable_antelope: require './sable_antelope'
    samango_monkey: require './samango_monkey'
    serval: require './serval'
    vervet: require './vervet'
    warthog: require './warthog'
    waterbuck: require './waterbuck'
    weasel: require './weasel'
    wild_dog: require './wild_dog'
    wildcat: require './wildcat'
    wildebeest: require './wildebeest'
    zebra: require './zebra'

  birds:
    crane: require './crane'
    ground_hornbill: require './ground_hornbill'
    secretary_bird: require './secretary_bird'
    vulture: require './vulture'

  reptiles:
    reptile: require './reptile'
    #crocodile: require './crocodile'
    #monitor_lizard: require './monitor_lizard'
    #pygmy_chameleon: require './pygmy_chameleon'
    #rock_python: require './rock_python'
    #tortoise: require './tortoise'
